#!/bin/bash


if [ $# -ne 1 ]
then
	echo "Usage: $0 [honeypot-number] "
	exit 1
fi

# Include the functions that we'll use between scripts
source /usr/hp/common_functions

#echo "Running tail on /var/log/auth.log in container #$1...";

sudo tail -fn0 /vz/private/$1/var/log/auth.log 2>> /usr/hp/monitor.log | while read line; do

	# Check if the log message is a conneciton/disconnection message
	# Case: Apr 2 11:25:42 ovzhost sshd[1128]: pam_unix(sshd:session): session opened for user root by (uid=0)
	# Apr  2 14:41:19 ovzhost sshd[874]: Accepted password for root from 206.196.184.90 port 53766 ssh2
	if echo "$line" | grep -Eq "ssh.*Accepted password for root" ;
	then
		log_write "$line"

		# Get the IP Address of the connecter
		ip="`echo $line | cut -d" " -f11`"

		# Get the port that they are connecting to
		port="`echo $line | cut -d" " -f13`"

		# Call the script to handle the new connections
		/usr/hp/on_connect $1 "$ip" "$port" "$line"

	# Case: Mar 16 16:18:41 ovzhost sshd[8588]: Received disconnect from 128.8.68.127: 11: disconnected by user
	# Apr  2 14:29:40 ovzhost sshd[1152]: pam_unix(sshd:session): session closed for user root
	elif echo "$line" | grep -Eq "ssh.*session closed for user root" ;
	then
		log_write "DISCONNECT?: $line"
		/usr/hp/recycle $1 "`get_id`"
	fi
done

echo "Exited loop - error?"
