#!/bin/bash

source /usr/hp/common_functions

if [ $# -ne 1 ]
then
	echo "Usage: $0 [honeypot-number] "
	exit 1
fi

sudo tail -fn0 /vz/private/$1/usr/hp/log_commands 2>> /usr/hp/monitor.log | while read line; do

	if [ "$line" == "connect" ]; then
		log_write "[CTID: $1] ['$line'] CONNECTION MADE"
		# Grab the IP and port from the connect data
		ip="`echo $line | cut -d" " -f2`"
		port="`echo $line | cut -d" " -f3`"
		# Call our on connect command
		/usr/hp/on_connect $1 $ip $port "$line"
	else
		# Get the url
		url="`/usr/hp/find_url $line`"
		log_write "[CTID: $1] ['$line'] [`get_id`] => URL: $url"
		# Now store the download from the url
		/usr/hp/store download $1 "$url"
	fi
done