#!/bin/bash

if [ $# -ne 2 ] && [ "$2" != "override" ]
then
	echo "You aren't using recycle correctly. 'recycle [ctid] [object id]'"
	exit 1
fi

source /usr/hp/common_functions

# log_write "CALLING RECYCLE WITH $1 and ID=$2 || [ -e $1.lock ] = `[ -e /usr/hp/$1.lock ]` and cat $1.lock = `cat $1.lock`"

# Make sure that a hacker was on the system before recycle was called 
# and that the recycle command is being called for the right hacker 
# (might be the wrong hacker because of being called via "at")
if [ "$2" == "override" ] || ([ -e /usr/hp/$1.lock ] && [ "`cat /usr/hp/$1.lock`" == "$2" ])
then

	log_write "RECYCLING HONEYPOT $1"

	# Remove the file that indicates that a hacker is on the system
	rm -f /usr/hp/$1.lock

	if [ "$2" != "override" ]
	then
		/usr/hp/store log $1 RECYCLE "Recycling container $1"
		# Get the disconnect time
		converted_time="`date +%s`"

		# Get the ID of the currently logged in hacker
		id="`cat /usr/hp/$1.lock`"

		# Log the disconnnect
		if [ ! -s ids_$1.log ]
		then
			# The file is empty, so echo the object id too
			echo "|$id|$converted_time" >> ids_$1.log
		else
			# Just echo the disconnect time
			echo "$converted_time" >> ids_$1.log
		fi
		# Set disconnect time and whether the hacker was kicked
		mongo_write "db.sessions.update({_id: ObjectId('`get_id`')}, {\$set: {disconnect: new Date()}})"
	fi

	# Backup important files in order to be able to access them later
	if [ ! -e /usr/hp/backups ]; then
		mkdir /usr/hp/backups/
	fi

	dir="`ls -t /usr/hp/backups | head -1`"
	dir=$((dir + 1))

	mkdir /usr/hp/backups/$dir/

	if sudo [ -e /vz/private/$1/usr/hp/log_commands ]; then
		sudo cp /vz/private/$1/usr/hp/log_commands /usr/hp/backups/$dir/
	fi
	if sudo [ -e /vz/private/$1/root/.bash_history ]; then
		sudo cp /vz/private/$1/root/.bash_history /usr/hp/backups/$dir/bash_history
	fi
	if sudo [ -e /vz/private/$1/var/log/auth.log ]; then
		sudo cp /vz/private/$1/var/log/auth.log /usr/hp/backups/$dir/
	fi

	# First stop monitoring commands
	sudo /usr/hp/hpctl stop $1

	# Stop and destroy the container
	sudo vzctl stop $1 > /dev/null 2>&1
	sudo vzctl destroy $1 > /dev/null 2>&1

	# Restore the snapshot
	sudo vzrestore /vz/dump/vzdump-openvz-$1*.tar $1 > /dev/null 2>&1

	# Start the container
	sudo vzctl start $1 > /dev/null 2>&1

	# Add internet
	sudo brctl addif br0 "veth$1.0" > /dev/null 2>&1

	# Restart monitoring for this honeypot
	/usr/hp/hpctl start $1
fi